# Generated by Django 5.2.6 on 2025-09-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="prodcts",
            new_name="product",
        ),
    ]
